services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: parliament-backend
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - ENV=${ENV}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - parliametrics-net

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: parliament-worker
    volumes:
      - ./backend:/backend
      - ./worker:/worker
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONPATH=/backend
    networks:
      - parliametrics-net

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: parliament-frontend-dev
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - backend
    networks:
      - parliametrics-net
      
networks:
  parliametrics-net:
    external: true
