services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: parliament-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/parliament

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: parliament-worker
    volumes:
      - ./backend:/backend
      - ./worker:/worker
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/parliament
      - PYTHONPATH=/backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: parliament-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: parliament-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: postgres:17.5
    container_name: parliament-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=parliament
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
