services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: parliament-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - ENV=production
      - DATABASE_URL=${DATABASE_URL}

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: parliament-worker
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONPATH=/backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: parliament-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
