services:
  db:
    image: postgres:17.5
    container_name: parliament-db
    restart: always
    ports:
      - ${DB_PORT_MAPPING:-}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - parliametrics-net

networks:
  parliametrics-net:

volumes:
  pgdata: